### PR TITLE
Update perlcassa.pm

### PR DESCRIPTION
**Pull request by 0yogue**
bulk insert to composite column fix

### CODE REVIEW

**Comment by mkjellman** [comment]
thanks!

**Comment by 0yogue** [comment]
I need of the a  support bulk insert better, i think in structure:

my %bulk = (
    # columns => value
    'MA:Boston'    => 'EST',
        'MA:Waltham'   => 'EST',
    'CA:Cupertino' => 'PDT', 
    'CA:Campbell'  => 'PDT'
);

$cass->bulk_insert(
    key => 'testkey',
    columns => \%bulk,
    ttl => 900,
    sep_char => ':' # split columns name to composite column
);

Thus the support will be better, what you think? 
I can apply this patch too?

**Comment by mkjellman** [comment]
a bit confused what you are proposing. could you explain a bit more?

**Comment by 0yogue** [comment]
The bulk insert as proposed is not working,
note that the hash structure is superimposed,
so that only the last key is inserted.

therefore propose a hash which is passed to the column name as concatenated key and the instruction of the parameter bulk_insert split key.

It is clearer?

**Comment by mkjellman** [comment]
yes, it is. i'm more surprised it's broken. i thought i had tested that. do you already have a proposed patch?

**Comment by 0yogue** [comment]
works, but not the best way, sending the patch later, tks.

**Comment by mkjellman** [comment]
marcioferreira: i reverted your patch. it broke some bulk tests i have for the module. can you please explain why you want to flip the order?

column => value makes since to me instead of value => column

**Comment by 0yogue** [comment]
mkjellman,

based on the example
https://github.com/mkjellman/perlcassa/blob/master/examples/bulk_insert.pl
I understand that you want a composite column name ('MA', 'Boston') with
value "EST", no?

What is your expected structure with the example of bulk insert. Perhaps
the comment in the code has confudido me.

I hope one method of doing bulk insert into composite type column name.

**Comment by mkjellman** [comment]
your patch unfortunately broke this from working:

my %bulk = (
   'col1'   => [$val1],
    'col2' => [$val2],
);

$obj->bulk_insert(
    'key'           => $key,
    'columns'       => \%bulk
);

but i understand what you are trying to accomplish. let me test off line a bit more.

**Comment by 0yogue** [comment]
I got confused by the comment code (# value => [column name]).

Can I send a patch that works for both cases.

Sorry about the confusion, the comment really got me fooled.

**Comment by mkjellman** [comment]
yeah this section of the code is horrible. apologies. if you get to it before me feel free to send a patch, otherwise i'll get to it tomorrow.

**Comment by 0yogue** [comment]
Do not worry, use your module and want to contribute! 

Drawing a parallel to work with tables, fields and records, I think the primary key, row key, must be in the bulk structure of the hash. 
I think the following structure/design: 

my %bulk = ( 
    "rowkey_1:$foo:$bar" => { 
        'name_pt1:name_pt2' => 'test', 
        'name_pt3:name_pt4' => 'test2' 
    } 
    "rowkey_2:$foo:$bar" => { 
        'name_vl1:name_vl2' => 'testtest' 
        'name_vl3:name_vl4' => 'test2test' 
    } 
); 

$obj->bulk_insert( 
    'data'                     => \%bulk, 
    'sep_char'              => qr/:/ 
    'split_rowkey'         => 1, 
    'split_columnname' => 1, 
); 

Perhaps there are better names than "split_rowkey/split_columnname" but I find it interesting that interface, what do you think? 

I need that structure very soon, if you can leave it with me and continue the line where you were.

**Comment by mkjellman** [comment]
the original goal was to implement column names as an array => val

that is the way i dealt with it everywhere else. I really don't like the other required params in bulk_insert, especially when we can use another data structure that doesn't require them.

i am a fan however of a hash of hashes containing multiple keys for the bulk insert. i need to look at the way thrift implements that.

**Comment by mkjellman** [comment]
example:

my %bulk = (
    ['key1'] => {
         ['colpt1', 'colpt2', 'colpt3'] => 'val1'
    }
);

**Comment by 0yogue** [comment]
Perfect! I had never used an array as hash keys!
Can I implement it, all right with you?

**Comment by mkjellman** [comment]
You are correct that in perl hash keys can only be strings. The only real way would be to use something like http://search.cpan.org/~fxn/Hash-MultiKey-0.06/MultiKey.pm but i'm not sure how viable this is. I think i now know why i had that comment there (thinking i could have a value => [colarray] to sidestep this but realized it was a clunky implementation as people don't think in that direction and reversed it.

**Comment by 0yogue** [comment]
Alright, let's work with your suggestion of design!
My concern was not just breaking backward compatibility with the module, if
you are the owner of this module allows breaking design, great! =)
Until next week have it working and sending the patch to discuss.

Another thing I want, if possible with you, is to work with binary CQL.

**Comment by mkjellman** [comment]
already working on the binary protocol :)

The current implementation is pretty broken so let's just fix it correctly.

**Pull request merged**
